<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework> <!-- Изменено на стабильную версию -->
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable> <!-- Включает строгую проверку null -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>NU1701;NU1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Современные версии, полностью совместимые с .NET 8/9/10 -->
    <PackageReference Include="HelixToolkit.Wpf" Version="2.25.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0" />
  </ItemGroup>

</Project>